name: "Check Git Status"
description: "Fail the workflow or git push based if git status is not clean."
inputs:
  fail-if-not-clean:
    description: "Fail the workflow if git status is not clean."
    required: false
    default: true
  push-if-not-clean:
    description: "Commit the changes and push them to the origin if git status is not clean."
    required: false
    default: false
  request-ch