name: "Check Git Status"
description: "Fail the workflow or git push based if git status is not clean."
inputs:
  fail-if-not-clean:
    description: "Fail the workflow if git status is not clean."
    required: false
    default: true
  push-if-not-clean:
    description: "Commit the changes and push them to the origin if git status is not clean."
    required: false
    default: false
  request-changes-if-not-clean:
    description: "Request change when in the context of a Pull Request if git status is not clean."
    required: false
    default: true
  github-token:
    description: "GitHub token to use when pushing new changes."
    required: false
    default: ${{ github.token }}
    deprecationMessage: "Please use the push-token input instead."
  push-token:
    description: "GitHub token to use when pushing new changes."
    required: false
    default: ${{ github.token }}
  request-changes-token:
    description: "GitHub token to use when requesting changes in a Pull Request."
    required: false
    default: ${{ github.token }}
  commit-message:
    description: "The