name: Ship

on:
  pull_request:
    branches: [main]
    types:
      [
        labeled,
        unlabeled,
        edited,
        closed,
        reopened,
        synchronize,
        review_requested,
        review_request_removed,
      ]
  pull_request_review:
    types: [submitted, edited, dismissed]
  check_run:
    type: [created, rerequested, completed]
  check_suite:
    types: [completed]
  workflow_run:
    branches: ['[0-9]+-[0-9]+-*']
    workflows: ['Test']
    types: [completed]

concurrency:
  group: |-
    ${{
      github.event.pull_request.number ||
      join(github.event.check_run.pull_requests.*.number,