
name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, '[0-9]+-[0-9]+-*']
  workflow_run:
    workflows: ['Test for Dependabot']
    types:
      - completed
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'Checkout a different git ref instead of the SHA from the GitHub event.'
        required: false
        type: string

jobs:
  test_clean:
    name: Test Clean
    if: |-
      ${{
        !startsWith(github.head_ref, 'workflows/tests/') && ((
          github.actor == 'dependabot[bot]' && 
          github.event_name != 'push' &&
          github.event_name != 'pull_request'
        ) || (
          github.actor != 'dependabot[bot]' &&
          github.event_name != 'workflow_run'
        ))
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'workflow_run' }}
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: ./
        id: test-action

      - name: Verify outputs
        env:
          TEST_ACTION_OUTPUT: ${{ steps.test-action.outputs.status }}
        run: |
          if [[ $TEST_ACTION_OUTPUT != "clean" ]]
          then
            exit 1;
          fi

  test_dirty_failure:
    name: Test Dirty Failure
    if: |-
      ${{
        !startsWith(github.head_ref, 'workflows/tests/') && ((
          github.actor == 'dependabot[bot]' && 
          github.event_name != 'push' &&
          github.event_name != 'pull_request'
        ) || (
          github.actor != 'dependabot[bot]' &&
          github.event_name != 'workflow_run'
        ))
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'workflow_run' }}

      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Make dirty
        run: |
          touch `git rev-parse --verify HEAD`

      - uses: ./
        id: test-action
        continue-on-error: true

      - name: Verify outputs
        env:
          TEST_ACTION_OUTPUT: ${{ steps.test-action.outputs.status }}
        run: |